<script>
  import { createEventDispatcher } from 'svelte'

  const dispatch = createEventDispatcher()
  // chip = "text to display", id = "unique id"
  // id possibly generated by uuid
  export let chips = []
</script>

<div class="chips">
  {#each chips as item (item.id)}
    <div class="chip noselect">
      <span>{item.chip}</span>
      <span class="close" on:click={() => dispatch('chipclose', { id: item.id })}>&times;</span>
    </div>
  {/each}
</div>

<style>
  .chips {
    display: block;
  }
  .chip {
    display: inline-block;
    height: 24px;
    border: 1px solid rgba(var(--chip-rgb), 0.3);
    font-family: var(--sans-serif);
    font-size: 13px;
    line-height: 1.5;
    padding: 1px 10px;
    white-space: nowrap;
    border-radius: 4px;
    margin: 0 7px 0 0;
    text-decoration: none;
    color: rgba(0, 0, 0, 0.76);
    -webkit-transition: all 100ms ease-out;
    -moz-transition: all 100ms ease-out;
    -ms-transition: all 100ms ease-out;
    -o-transition: all 100ms ease-out;
    transition: all 100ms ease-out;
  }
  .chip:hover {
    border-color: rgba(var(--chip-rgb), 0.6);
  }
  .close {
    cursor: pointer;
    background-color: rgba(var(--chip-rgb), 0.16);
    width: 15px;
    height: 15px;
    display: inline-block;
    vertical-align: middle;
    margin-left: 3px;
    border-radius: 2px;
    line-height: 1;
    text-align: center;
    color: rgba(0, 0, 0, 0.76);
    left: 2px;
  }
  .close:hover {
    background-color: rgba(var(--chip-rgb), 0.32);
  }
</style>
