export default {
  stage: 'prepare:GET',
  data: {
    rows: 12389,
    target: null,
    nextAvialableId: '25',
    typeConversion: {
      // from Number
      Number: ['Category', 'Numeric'],
      // from Text
      Text: ['Category', 'Text'],
      // from Timestamp
      Timestamp: ['Category', 'Timestamp'],
      // from Category
      Category: ['Text', 'Category'],
    },
    cols: [
      {
        id: '1',
        name: 'company_permalink',
        type: 'Text',
        sample: [
          '/organization/wireover',
          '/organization/energyhub',
          '/organization/memento',
          '/organization/connotate',
          '/organization/connotate',
          '/organization/mineraltree',
          '/organization/mineraltree',
          '/organization/veracode',
          '/organization/woodpellets-com',
          '/organization/american-biomass',
          '/organization/attendware',
          '/organization/kaltura',
          '/organization/abilto',
          '/organization/tokita-investments',
          '/organization/fishki',
          '/organization/social-beyond',
          '/organization/audiosnaps',
          '/organization/pro-pharmaceuticals',
          '/organization/pro-pharmaceutical',
        ],
        imputable: false,
      },
      {
        id: '2',
        name: 'company_name',
        type: 'Category',
        sample: [
          'WireOver',
          'EnergyHub',
          'Memento',
          'Connotate',
          'Connotate',
          'MineralTree',
          'MineralTree',
          'Veracode',
          'woodpellets.com',
          'American Biomass',
          'Attend.com',
          'Kaltura',
          'AbilTo',
          'Tokita Investments',
          'Fishki',
          'Social & Beyond',
          'AudioSnaps',
          'Galectin Therapeutics',
          'Galectin Therapeutics',
        ],
        imputable: true,
      },
      {
        id: '3',
        name: 'company_Category_list',
        type: 'Text',
        sample: [
          '|Curated Web|',
          '|Clean Technology|',
          '|Security|Enterprise Software|',
          '|Enterprises|Data Mining|Business Intelligence|Big Data|Analytics|',
          '|Enterprises|Data Mining|Business Intelligence|Big Data|Analytics|',
          '|Analytics|',
          '|Analytics|',
          '|Security|',
          '|Clean Technology|',
          '|Clean Technology|',
          '|Software|',
          '|Web CMS|Content|Video Editing|Open Source|Music|Web Tools|Media|Collaboration|Video|Software|',
          '|Teachers|Health and Wellness|VoIP|Technology|Web Development|Internet|Therapeutics|Medical|Psychology|Heathcare|Curated Web|',
          '|Consulting|',
          '|Games|',
          '|Advertising|',
          '|Mobile|',
          '|Biotechnology|',
          '|Biotechnology|',
        ],
        imputable: true,
      },
      {
        id: '4',
        name: 'company_market',
        type: 'Category',
        sample: [
          'Curated Web',
          'Clean Technology',
          'Enterprise Software',
          'Analytics',
          'Analytics',
          'Analytics',
          'Analytics',
          'Security',
          'Clean Technology',
          'Clean Technology',
          'Software',
          'Collaboration',
          'Curated Web',
          'Consulting',
          'Games',
          'Advertising',
          'Mobile',
          'Biotechnology',
          'Biotechnology',
        ],
        imputable: true,
      },
      {
        id: '5',
        name: 'company_country_code',
        type: 'Category',
        sample: [
          '',
          'USA',
          'USA',
          'USA',
          'USA',
          'USA',
          'USA',
          'USA',
          'USA',
          'USA',
          'USA',
          'USA',
          'USA',
          'JPN',
          'RUS',
          'ESP',
          '',
          'USA',
          'USA',
        ],
        imputable: true,
      },
      {
        id: '6',
        name: 'company_state_code',
        type: 'Category',
        sample: [
          '',
          'NY',
          'MA',
          'NJ',
          'NJ',
          'MA',
          'MA',
          'MA',
          'NH',
          'NH',
          'MA',
          'NY',
          'NY',
          '',
          '',
          '',
          '',
          'GA',
          'GA',
        ],
        imputable: false,
      },
      {
        id: '7',
        name: 'company_region',
        type: 'Category',
        sample: [
          '',
          'New York City',
          'Boston',
          'Newark',
          'Newark',
          'Boston',
          'Boston',
          'Boston',
          'NH - Other',
          'NH - Other',
          'Boston',
          'New York City',
          'New York City',
          'JPN - Other',
          'RUS - Other',
          'Barcelona',
          '',
          'Atlanta',
          'Atlanta',
        ],
        imputable: true,
      },
      {
        id: '8',
        name: 'company_city',
        type: 'Category',
        sample: [
          '',
          'Brooklyn',
          'Concord',
          'New Brunswick',
          'New Brunswick',
          'Cambridge',
          'Cambridge',
          'Burlington',
          'Goffstown',
          'Goffstown',
          'Boston',
          'New York',
          'New York',
          'Okinawa Ken',
          'Rus',
          'Barcelona',
          '',
          'Norcross',
          'Norcross',
        ],
        imputable: false,
      },
      {
        id: '9',
        name: 'investor_permalink',
        type: 'Text',
        sample: [
          '',
          'Brooklyn',
          'Concord',
          'New Brunswick',
          'New Brunswick',
          'Cambridge',
          'Cambridge',
          'Burlington',
          'Goffstown',
          'Goffstown',
          'Boston',
          'New York',
          'New York',
          'Okinawa Ken',
          'Rus',
          'Barcelona',
          '',
          'Norcross',
          'Norcross',
        ],
        imputable: false,
      },
      {
        id: '10',
        name: 'investor_name',
        type: 'Category',
        sample: [
          '.406 Ventures',
          '.406 Ventures',
          '.406 Ventures',
          '.406 Ventures',
          '.406 Ventures',
          '.406 Ventures',
          '.406 Ventures',
          '.406 Ventures',
          '.406 Ventures',
          '.406 Ventures',
          '.406 Ventures',
          '.406 Ventures',
          '.406 Ventures',
          '01Startups',
          '101 Startups',
          '101 Startups',
          '101 Startups',
          '10X Fund LP',
          '10X Fund LP',
        ],
        imputable: false,
      },
      {
        id: '11',
        name: 'investor_Category_list',
        type: 'Category',
        sample: ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
        imputable: true,
      },
      {
        id: '12',
        name: 'investor_market',
        type: 'Category',
        sample: ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
        imputable: true,
      },
      {
        id: '13',
        name: 'investor_country_code',
        type: 'Category',
        sample: [
          'USA',
          'USA',
          'USA',
          'USA',
          'USA',
          'USA',
          'USA',
          'USA',
          'USA',
          'USA',
          'USA',
          'USA',
          'USA',
          '',
          '',
          '',
          '',
          '',
          '',
        ],
        imputable: true,
      },
      {
        id: '14',
        name: 'investor_state_code',
        type: 'Category',
        sample: ['300', '220', '120'],
        imputable: false,
      },
      {
        id: '15',
        name: 'investor_region',
        type: 'Category',
        sample: [
          'Boston',
          'Boston',
          'Boston',
          'Boston',
          'Boston',
          'Boston',
          'Boston',
          'Boston',
          'Boston',
          'Boston',
          'Boston',
          'Boston',
          'Boston',
          '',
          '',
          '',
          '',
          '',
          '',
        ],
        imputable: false,
      },
      {
        id: '16',
        name: 'investor_city',
        type: 'Category',
        sample: [
          'Boston',
          'Boston',
          'Boston',
          'Boston',
          'Boston',
          'Boston',
          'Boston',
          'Boston',
          'Boston',
          'Boston',
          'Boston',
          'Boston',
          'Boston',
          '',
          '',
          '',
          '',
          '',
          '',
        ],
        imputable: false,
      },
      {
        id: '17',
        name: 'funding_round_permalink',
        type: 'Text',
        sample: [
          '/funding-round/1286ecd15fac08512e75d0fb64a394e1',
          '/funding-round/aa4f931d17112ba9dac4d149b22923e0',
          '/funding-round/178fdc6b1f3f0cb0d26b11303c532c15',
          '/funding-round/eb9c63d7eabadbe8f21c2e10aed9359d',
          '/funding-round/f076023550950ab4c3ae4343faba1dd3',
          '/funding-round/199f917c2d5b783caaa2a649379dd46a',
          '/funding-round/c5282eea0a3d469e7ef5d7a6d62e93ac',
          '/funding-round/db676dfcfaf44bde20751959cef3d487',
          '/funding-round/57d79a986d387e98d9356a4b8126c205',
          '/funding-round/505b323bec839190fe0d25082fbc3ea1',
          '/funding-round/e9d3a39c27bae7ecc1994e95e5d35a92',
          '/funding-round/6ff90875d9159b89aa6545d23f32695d',
          '/funding-round/8a033677a77513a346ecf039483622be',
          '/funding-round/3b01561dd8c054727c9ddc0705a73f4c',
          '/funding-round/2aaa61db661ff14069e37d98b088a1ae',
          '/funding-round/f5fc81877ddc1543c4f09f2ff68b6def',
          '/funding-round/e9e418596c68cae78d657bf3adf07d89',
          '/funding-round/1856ca603db68eaa89e7917293cf1f58',
          '/funding-round/820f3a91cb540b84632181cbe5948437',
        ],
        imputable: false,
      },
      {
        id: '18',
        name: 'funding_round_type',
        type: 'Category',
        sample: [
          'seed',
          'venture',
          'unknown',
          'venture',
          'venture',
          'venture',
          'unknown',
          'venture',
          'venture',
          'venture',
          'venture',
          'venture',
          'venture',
          'seed',
          'seed',
          'seed',
          'seed',
          'venture',
          'venture',
        ],
        imputable: false,
      },
      {
        id: '19',
        name: 'funding_round_code',
        type: 'Category',
        sample: [
          '',
          'b',
          '',
          'b',
          'a',
          'a',
          '',
          'b',
          'a',
          'a',
          'a',
          'b',
          'a',
          '',
          '',
          '',
          '',
          'b',
          'b',
        ],
        imputable: false,
      },
      {
        id: '20',
        name: 'funded_at',
        type: 'Timestamp',
        sample: [
          '2012-08-01',
          '2011-08-25',
          '2007-05-09',
          '2012-04-12',
          '2010-06-08',
          '2012-06-27',
          '2011-11-09',
          '2007-01-22',
          '2008-06-03',
          '2008-05-15',
          '2013-06-25',
          '2008-06-20',
          '2013-05-14',
          '2013-09-26',
          '2013-11-18',
          '2013-07-16',
          '2013-12-17',
          '2009-02-12',
          '2010-05-10',
        ],
        imputable: false,
      },
      {
        id: '21',
        name: 'funded_month',
        type: 'Category',
        sample: [
          '2012-08',
          '2011-08',
          '2007-05',
          '2012-04',
          '2010-06',
          '2012-06',
          '2011-11',
          '2007-01',
          '2008-06',
          '2008-05',
          '2013-06',
          '2008-06',
          '2013-05',
          '2013-09',
          '2013-11',
          '2013-07',
          '2013-12',
          '2009-02',
          '2010-05',
        ],
        imputable: false,
      },
      {
        id: '22',
        name: 'funded_quarter',
        type: 'Category',
        sample: [
          '2012-Q3',
          '2011-Q3',
          '2007-Q2',
          '2012-Q2',
          '2010-Q2',
          '2012-Q2',
          '2011-Q4',
          '2007-Q1',
          '2008-Q2',
          '2008-Q2',
          '2013-Q2',
          '2008-Q2',
          '2013-Q2',
          '2013-Q3',
          '2013-Q4',
          '2013-Q3',
          '2013-Q4',
          '2009-Q1',
          '2010-Q2',
        ],
        imputable: false,
      },
      {
        id: '23',
        name: 'funded_year',
        type: 'Number',
        sample: [
          2012,
          2011,
          2007,
          2012,
          2010,
          2012,
          2011,
          2007,
          2008,
          2008,
          2013,
          2008,
          2013,
          2013,
          2013,
          2013,
          2013,
          2009,
          2010,
        ],
        imputable: true,
      },
      {
        id: '24',
        name: 'raised_amount_usd',
        type: 'Number',
        sample: [
          '',
          14500000,
          7500000,
          7000000,
          5250000,
          6300000,
          1500000,
          19500000,
          4000000,
          4030000,
          1000000,
          21000000,
          3000000,
          5000,
          1200000,
          523315,
          '',
          1800000,
          570000,
        ],
        imputable: true,
      },
    ],
  },
}
